
# get methods

# get all
GET http://localhost:4000/api/ HTTP/1.1
### 


# get by id

GET http://localhost:4000/api/63107d1c20515abada1725ba HTTP/1.1

###


#### posts methods ####


POST http://localhost:8090/api/users HTTP/1.1
content-type: application/json


{
    "email": "medy.ego@gmail.com",
   
    "password":"hello i am currently under the water, please help",
    "passwordConfirm":"hello i am currently under the water, please help"
}